version: '2'
services:
  mysql:
    image: mysql:5.6
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/database:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass

  maxvell:
    image: zendesk/maxwell
    ports:
      - "8084:8081"
    links:
      - mysql
      - kafka
    depends_on:
      - mysql
      - kafka
      - zookeeper
    environment:
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
      MYSQL_HOST: mysql
      KAFKA_HOST: kafka
      KAFKA_PORT: 9092


  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    build: https://github.com/wurstmeister/kafka-docker.git
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.32.135
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  node:
    image: "node:8"
    user: "node"
    working_dir: /home/node/app
    depends_on:
      - kafka
    environment:
      - NODE_ENV=production
    volumes:
      - ./node:/home/node/app
    expose:
      - "8080"
    ports:
      - "8080:8081"
    command: "npm run kafka"
    links:
      - redis
  
  redisCommander:
    image: tenstartups/redis-commander
    command: --redis-host redis
    links:
      - redis
    ports:
      - "8081:8081"
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql
    depends_on:
      - mysql
    restart: always
    ports:
      - "8082:80"
    environment:
      PMA_HOSTS: mysql

  redis:
    image: redis:2.8
    restart: always
    ports:
      - "6379:6379"